# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Floyd, Web and SalesForce Developer
email: mikefloyd21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mike Floyd is a Full Stack Web Developer, SalesForce Developer, and Certified SalesForce Admin with over 15 years of experience creating and supporting enterprise applications. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mikefloyd21
github_username:  mikefloyd21

# Build settings
markdown: kramdown
